USE SUCOS_VENDAS;

SELECT * FROM TABELA_DE_VENDEDORES;

/*Alterar o campo/coluna para que aceite valores nulos.*/
ALTER TABLE TABELA_DE_VENDEDORES ALTER COLUMN MATRICULA CHAR(5) NOT NULL;

/*Criar a chave primária*/
ALTER TABLE TABELA_DE_VENDEDORES
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED (MATRICULA);