USE SUCOS_VENDAS;

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_VENDEDORES;

/*Exluindo o produto 10088126 da linha 5*/
DELETE FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '1088126';

/*Excluindo a vendedora de matricula 00236 que pediu demissão*/
DELETE FROM TABELA_DE_VENDEDORES
WHERE MATRICULA = '00236';

