INSERT INTO TABELA_DE_PRODUTOS
VALUES
('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',7);

SELECT * FROM TABELA_DE_PRODUTOS;

DELETE FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '107680'
